services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/playlistgen
      - REDIS_URL=redis://localhost:6379
      - PYTHONPATH=/workspaces
      - NODE_ENV=development

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: playlistgen
    # No external port mapping - accessed via internal network only

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-devcontainer}-network
